### ISSUE TITLE
Wrong request URL when the app has sub path

### ISSUE THREAD

**Issue by skillcrushbinguyen** [RonSijm/RonSijm.Blazyload#3]
Hi RonSijm,
Thank you for your fantastic library, I got an error when loading DLL from the app has the non-root path

This is my example of a loading error
![image](https://github.com/user-attachments/assets/9a0c9d79-e22c-4687-9330-9f78698c21cc)

This is my base root from the index.html
![image](https://github.com/user-attachments/assets/1a17588c-e415-4e1c-aa79-892e3f630de5)

I am not sure this is a bug. Could you please help me confirm? Thank you!

**Comment by RonSijm** [comment]
Hey, thanks.

It's hard to tell whether this is a bug in the library or not. Maybe you could post a small sample project that reproduces this, if you want to me check it out?

Though 404 just means that it can't find the file. So you should probably check that the dll it's trying to fetch is actually there. 

Your usecase sounds close to the CustomPathing example. See:
https://github.com/RonSijm/RonSijm.Blazyload/blob/main/Examples/CustomPathing/RonSijm.Demo.Blazyload.CustomPathing.Host/RonSijm.Demo.Blazyload.CustomPathing.Host.csproj

I think what I'm doing there in the PostBuildEvent is to move dlls to a different folder, you might need something similar like that I guess

**Comment by skillcrushbinguyen** [comment]
I created a sample and it work perfectly. So I will close this ticket and check again. Thank you for your support

**Comment by peterthorpe81** [comment]
Just adding that I had the same issue. I think there is a pathing mistake somewhere as I get the "//" issue on a brand new .net 8 template project with <base href="/" /> 

I have resolved it for now with a custom path.

**Comment by peterthorpe81** [comment]
This seems to fix it thanks
