### ISSUE TITLE
Disable PDB file load

### ISSUE THREAD

**Issue by peterthorpe81** [RonSijm/RonSijm.Blazyload#4]
I am attempting to load a third-party assembly through this project. It looks like the code is setup to attempt to load the .wasm file and then the .pdb file. In this case I don't have a .pdb file so I get a web browser console error and the assembly loading appears to be halted.

I think there should either be better handling when the pdb doesn't exist or a configuration option to disable pdb loading.

The project looks great I have managed to load my assemblies using the normal assembly loader for now and used this project to add the service dependency it needs.

**Comment by RonSijm** [comment]
Alright, you can now disable pdb. There's also a try/catch around it, so if pdb loading doesn't work, it only shows a console output (in debug mode)

Lemme know if that fixes it :)

https://github.com/RonSijm/RonSijm.Blazyload/commit/ba012ee6b0aa9d5be96f6b00be30a468945a9ca4

**Comment by peterthorpe81** [comment]
Awesome the try catch and config option both appear to work. Thanks for the rapid update.
